### ISSUE TITLE
Stack trace on Jenkins startup WARNING: failed to send event to listener of class org.jenkinsci.plugins.pipeline.milestone.MilestoneStepExecution$CleanupJobsOnDelete

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#147]
By default, it should be no stack traces when starting Jenkins as code
This one began to appear recently. From the first look, it doesn't cause any disturbances but still have to be investigated and fixed

```
jmaster_1       | WARNING: failed to send event to listener of class org.jenkinsci.plugins.pipeline.milestone.MilestoneStepExecution$CleanupJobsOnDelete
jmaster_1       | java.lang.NullPointerException
jmaster_1       | 	at org.jenkinsci.plugins.pipeline.milestone.MilestoneStepExecution$CleanupJobsOnDelete.onDeleted(MilestoneStepExecution.java:348)
jmaster_1       | 	at hudson.model.listeners.ItemListener$4.apply(ItemListener.java:205)
jmaster_1       | 	at hudson.model.listeners.ItemListener$4.apply(ItemListener.java:203)
jmaster_1       | 	at hudson.model.listeners.ItemListener.forAll(ItemListener.java:167)
jmaster_1       | 	at hudson.model.listeners.ItemListener.fireOnDeleted(ItemListener.java:203)
jmaster_1       | 	at jenkins.model.Jenkins.onDeleted(Jenkins.java:2918)
jmaster_1       | 	at jenkins.model.Jenkins.onDeleted(Jenkins.java:324)
jmaster_1       | 	at hudson.model.AbstractItem.delete(AbstractItem.java:572)
jmaster_1       | 	at hudson.model.Job.delete(Job.java:683)
jmaster_1       | 	at hudson.model.Item$delete.call(Unknown Source)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
jmaster_1       | 	at initialjobs$_run_closure1.doCall(initialjobs.groovy:18)
jmaster_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jmaster_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jmaster_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jmaster_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
jmaster_1       | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
jmaster_1       | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
jmaster_1       | 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
jmaster_1       | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
jmaster_1       | 	at groovy.lang.Closure.call(Closure.java:414)
jmaster_1       | 	at groovy.lang.Closure.call(Closure.java:430)
jmaster_1       | 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5228)
jmaster_1       | 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2107)
jmaster_1       | 	at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
jmaster_1       | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
jmaster_1       | 	at initialjobs.run(initialjobs.groovy:15)
jmaster_1       | 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
jmaster_1       | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
jmaster_1       | 	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
jmaster_1       | 	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
jmaster_1       | 	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
jmaster_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jmaster_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jmaster_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jmaster_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
jmaster_1       | 	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jmaster_1       | 	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jmaster_1       | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
jmaster_1       | 	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1085)
jmaster_1       | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
jmaster_1       | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jmaster_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
jmaster_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
jmaster_1       | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Andrey9kin** [comment]
Fixed by #161
